# Generated by Django 5.2.4 on 2025-12-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_airecognitionresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
